version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    links:
      - mongo
      - postgres
    environment:
      DATA_SOURCE: 'mongo'
  mongo:
    container_name: mongo
    image: mongo
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"
  postgres:
    container_name: postgres
    image: postgres
    # volumes:
    #   - ./pgdata:/tmp
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: jscatalyst

# volumes:
#   pgdata:
#     external: true
