/**
 * An array of component names to be used for UIBuilder.
 *
 */
export default [
  { text: 'D3 Bar Chart', value: 'D3BarChart' },
  { text: 'D3 Box Plot', value: 'D3BoxPlot' },
  { text: 'D3 Bubble Chart', value: 'D3BubbleChart' },
  { text: 'D3 Bullet Chart', value: 'D3BulletChart' },
  { text: 'D3 Dendrogram', value: 'D3Dendrogram' },
  { text: 'D3 Difference Chart', value: 'D3DifferenceChart' },
  { text: 'D3 Force Directed Graph', value: 'D3ForceDirectedGraph' },
  { text: 'D3 Gantt Chart', value: 'D3GanttChart' },
  { text: 'D3 Heat Map', value: 'D3HeatMap' },
  { text: 'D3 Histogram', value: 'D3Histogram' },
  { text: 'D3 Horizon Chart', value: 'D3HorizonChart' },
  { text: 'D3 Line Chart', value: 'D3LineChart' },
  { text: 'D3 Line Chart Zoomable', value: 'D3LineChartZoomable' },
  { text: 'D3 Line Plot', value: 'D3LinePlot' },
  { text: 'D3 Pie Chart', value: 'D3PieChart' },
  { text: 'D3 Punch Card', value: 'D3PunchCard' },
  { text: 'D3 Scatterplot', value: 'D3Scatterplot' },
  { text: 'D3 Stacked Bar Chart', value: 'D3StackedBarChart' },
  { text: 'D3 Stream Graph', value: 'D3StreamGraph' },
  { text: 'D3 Sunburst', value: 'D3Sunburst' },
  { text: 'D3 Two Line Plot', value: 'D3TwoLinePlot' },
  { text: 'D3 U S Map', value: 'D3USMap' },
  { text: 'D3 World Map', value: 'D3WorldMap' },
  { text: 'Chartjs Bar Chart', value: 'ChartjsBarChart' },
  { text: 'Chartjs Bar Line Chart', value: 'ChartjsBarLineChart' },
  { text: 'Chartjs Bubble Chart', value: 'ChartjsBubbleChart' },
  { text: 'Chartjs Line Chart', value: 'ChartjsLineChart' },
  { text: 'Chartjs Pie Chart', value: 'ChartjsPieChart' },
  { text: 'Chartjs Polar Chart', value: 'ChartjsPolarChart' },
  { text: 'Chartjs Radar Chart', value: 'ChartjsRadarChart' },
  { text: 'Chartjs Scatter Chart', value: 'ChartjsScatterChart' },
  // { text: 'Chartist Bar Chart', value: 'ChartistBarChart' },
  // { text: 'Chartist Line Chart', value: 'ChartistLineChart' },
  // { text: 'Chartist Pie Chart', value: 'ChartistPieChart' },
]
